In [1]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

C:\Python\Anaconda3-52\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [24]:
train =pd.read_csv('C:\\Users\Ente_LJS\\Anaconda_src\\Semi_Project_1pick\\train.csv')
test = pd.read_csv('C:\\Users\Ente_LJS\\Anaconda_src\\Semi_Project_1pick\\test.csv')
test_ids = test.Id

In [3]:
# dependency 값이 yes, no 포함하고 있어서 sqbdependecy에 루트 씌워서 채우기
train['dependency'] = np.sqrt(train['SQBdependency'])
test['dependency'] = np.sqrt(test['SQBdependency'])

In [4]:
# edjefa 'no'를 0으로
train.loc[train['edjefa'] == "no", "edjefa"] = 0
train.loc[train['edjefe'] == "no", "edjefe"] = 0
test.loc[test['edjefa'] == "no", "edjefa"] = 0
test.loc[test['edjefe'] == "no", "edjefe"] = 0

In [5]:
# edjefa 가 yes 인 경우 + 세대주인경우 escolari 값으로 채워주기
train.loc[(train['edjefa'] == "yes") & (train['parentesco1'] == 1), "edjefa"] = train.loc[(train['edjefa'] == "yes") & (train['parentesco1'] == 1), "escolari"]
train.loc[(train['edjefe'] == "yes") & (train['parentesco1'] == 1), "edjefe"] = train.loc[(train['edjefe'] == "yes") & (train['parentesco1'] == 1), "escolari"]

test.loc[(test['edjefa'] == "yes") & (test['parentesco1'] == 1), "edjefa"] = test.loc[(test['edjefa'] == "yes") & (test['parentesco1'] == 1), "escolari"]
test.loc[(test['edjefe'] == "yes") & (test['parentesco1'] == 1), "edjefe"] = test.loc[(test['edjefe'] == "yes") & (test['parentesco1'] == 1), "escolari"]

In [6]:
# edjefa 'yes'를 4로
train.loc[train['edjefa'] == "yes", "edjefa"] = 4
train.loc[train['edjefe'] == "yes", "edjefe"] = 4

test.loc[test['edjefa'] == "yes", "edjefa"] = 4
test.loc[test['edjefe'] == "yes", "edjefe"] = 4

In [7]:
# int로 변환
train['edjefe'] = train['edjefe'].astype("int")
train['edjefa'] = train['edjefa'].astype("int")
test['edjefe'] = test['edjefe'].astype("int")
test['edjefa'] = test['edjefa'].astype("int")
train['dependency'] = train['dependency'].astype("int")
test['dependency'] = test['dependency'].astype("int")

In [8]:
# create feature with max education of either head of household
train['edjef'] = np.max(train[['edjefa','edjefe']], axis=1)
test['edjef'] = np.max(test[['edjefa','edjefe']], axis=1)

In [9]:
# na값 채우기
train['v2a1']=train['v2a1'].fillna(0)
test['v2a1']=test['v2a1'].fillna(0)

test['v18q1']=test['v18q1'].fillna(0)
train['v18q1']=train['v18q1'].fillna(0)

train['rez_esc']=train['rez_esc'].fillna(0)
test['rez_esc']=test['rez_esc'].fillna(0)

train.loc[train.meaneduc.isnull(), "meaneduc"] = 0
train.loc[train.SQBmeaned.isnull(), "SQBmeaned"] = 0

test.loc[test.meaneduc.isnull(), "meaneduc"] = 0
test.loc[test.SQBmeaned.isnull(), "SQBmeaned"] = 0

In [10]:
needless_cols = ['r4t3', 'tamhog', 'tamviv', 'hhsize', 'v18q', 'v14a', 'agesq',
                 'mobilephone', 'female', 'Id','edjefe','edjefa', 'idhogar']

In [11]:
train = train.drop(needless_cols, axis=1)
test = test.drop(needless_cols, axis=1)

In [12]:
train

v2a1  hacdor  rooms  hacapo  refrig  v18q1  r4h1  r4h2  r4h3  r4m1  \
0     190000.0       0      3       0       1    0.0     0     1     1     0   
1     135000.0       0      4       0       1    1.0     0     1     1     0   
2          0.0       0      8       0       1    0.0     0     0     0     0   
3     180000.0       0      5       0       1    1.0     0     2     2     1   
4     180000.0       0      5       0       1    1.0     0     2     2     1   
5     180000.0       0      5       0       1    1.0     0     2     2     1   
6     180000.0       0      5       0       1    1.0     0     2     2     1   
7     130000.0       1      2       0       1    0.0     0     1     1     2   
8     130000.0       1      2       0       1    0.0     0     1     1     2   
9     130000.0       1      2       0       1    0.0     0     1     1     2   
10    130000.0       1      2       0       1    0.0     0     1     1     2   
11    100000.0       0      3       0       1    0.0     0     0     0     0   
12    100000.0       0      3       0       1    0.0     0     0     0     0   
13         0.0       0      4       0       1    1.0     0     1     1     0   
14         0.0       0      4       0       1    1.0     0     1     1     0   
15     90000.0       1      2       0       1    0.0     0     2     2     0   
16     90000.0       1      2       0       1    0.0     0     2     2     0   
17     90000.0       1      2       0       1    0.0     0     2     2     0   
18     90000.0       1      2       0       1    0.0     0     2     2     0   
19    215000.0       0      4       0       1    0.0     0     1     1     0   
20    215000.0       0      4       0       1    0.0     0     1     1     0   
21    150000.0       0      3       0       1    0.0     0     1     1     0   
22    150000.0       0      3       0       1    0.0     0     1     1     0   
23    100000.0       1      1       1       1    0.0     0     2     2     0   
24    100000.0       1      1       1       1    0.0     0     2     2     0   
25    100000.0       1      1       1       1    0.0     0     2     2     0   
26         0.0       0      5       0       1    0.0     0     1     1     0   
27    120000.0       0      4       0       1    1.0     0     2     2     0   
28    120000.0       0      4       0       1    1.0     0     2     2     0   
29    120000.0       0      4       0       1    1.0     0     2     2     0   
...        ...     ...    ...     ...     ...    ...   ...   ...   ...   ...   
9527       0.0       0      5       0       1    0.0     2     1     3     0   
9528   45000.0       0      3       0       0    0.0     0     0     0     0   
9529       0.0       0      1       0       1    0.0     0     1     1     0   
9530       0.0       0      1       0       1    0.0     0     1     1     0   
9531   70000.0       0      4       0       1    0.0     0     2     2     0   
9532   70000.0       0      4       0       1    0.0     0     2     2     0   
9533   70000.0       0      4       0       1    0.0     0     2     2     0   
9534       0.0       0      7       0       1    0.0     0     1     1     0   
9535       0.0       0      4       0       0    0.0     1     1     2     2   
9536       0.0       0      4       0       0    0.0     1     1     2     2   
9537       0.0       0      4       0       0    0.0     1     1     2     2   
9538       0.0       0      4       0       0    0.0     1     1     2     2   
9539       0.0       0      4       0       0    0.0     1     1     2     2   
9540       0.0       0      3       0       0    0.0     2     2     4     0   
9541       0.0       0      3       0       0    0.0     2     2     4     0   
9542       0.0       0      3       0       0    0.0     2     2     4     0   
9543       0.0       0      3       0       0    0.0     2     2     4     0   
9544       0.0       0      3       0       0    0.0     2     2     4     0   
9545   465

In [13]:
test

v2a1  hacdor  rooms  hacapo  refrig  v18q1  r4h1  r4h2  r4h3  r4m1  \
0           0.0       0      5       0       1    0.0     1     1     2     0   
1           0.0       0      5       0       1    0.0     1     1     2     0   
2           0.0       0      5       0       1    0.0     1     1     2     0   
3           0.0       0     14       0       1    1.0     0     1     1     0   
4      175000.0       0      4       0       1    1.0     0     0     0     0   
5      400000.0       0      3       0       1    1.0     0     0     0     0   
6      400000.0       0      3       0       1    1.0     0     0     0     0   
7      300000.0       0      6       0       1    1.0     0     0     0     0   
8      300000.0       0      6       0       1    1.0     0     0     0     0   
9           0.0       0      6       0       1    0.0     0     0     0     0   
10      90000.0       0      5       0       1    0.0     0     1     1     0   
11      90000.0       0      5       0       1    0.0     0     1     1     0   
12      90000.0       0      5       0       1    0.0     0     1     1     0   
13     200000.0       0      5       0       1    0.0     0     2     2     0   
14     200000.0       0      5       0       1    0.0     0     2     2     0   
15     200000.0       0      5       0       1    0.0     0     2     2     0   
16     200000.0       0      5       0       1    0.0     0     2     2     0   
17     200000.0       0      5       0       1    0.0     0     2     2     0   
18     200000.0       0      5       0       1    0.0     0     2     2     0   
19     240000.0       0      6       0       1    0.0     0     3     3     0   
20     240000.0       0      6       0       1    0.0     0     3     3     0   
21     240000.0       0      6       0       1    0.0     0     3     3     0   
22          0.0       0      5       0       1    0.0     0     0     0     0   
23          0.0       0      5       0       1    0.0     0     0     0     0   
24     210000.0       0      5       0       1    2.0     0     1     1     2   
25     210000.0       0      5       0       1    2.0     0     1     1     2   
26     210000.0       0      5       0       1    2.0     0     1     1     2   
27     210000.0       0      5       0       1    2.0     0     1     1     2   
28          0.0       0      8       0       1    1.0     0     2     2     0   
29          0.0       0      8       0       1    1.0     0     2     2     0   
...         ...     ...    ...     ...     ...    ...   ...   ...   ...   ...   
23826       0.0       0      1       0       0    0.0     1     0     1     0   
23827       0.0       0      4       0       1    0.0     0     1     1     0   
23828       0.0       0      4       0       1    0.0     0     1     1     0   
23829       0.0       0      4       0       1    0.0     0     1     1     0   
23830   46500.0       0      5       0       1    0.0     0     1     1     0   
23831   46500.0       0      5       0       1    0.0     0     1     1     0   
23832       0.0       0      3       0       1    0.0     0     2     2     0   
23833       0.0       0      3       0       1    0.0     0     2     2     0   
23834       0.0       0      3       0       1    0.0     0     2     2     0   
23835       0.0       0      4       0       0    0.0     1     0     1     0   
23836       0.0       0      4       0       0    0.0     1     0     1     0   
23837       0.0       0      4       0       1    0.0     1     1     2     1   
23838       0.0       0      4       0       1    0.0     1     1     2     1   
23839       0.0       0      4       0       1    0.0     1     1     2     1   
23840       0.0       0      4       0       1    0.0     1     1     2     1   
23841       0.0       0      4       0       1    0.0     1     1     2     1   
23842       0.0       0      4       0       1    0.0     1     1     2     1   
23843       0.0       0      5       0    

In [14]:
df_x1 = train.drop(["Target"],1)
df_y = pd.DataFrame(train['Target'])
df_y['Target']=df_y['Target']-1
df_y.head()

Target
0       3
1       3
2       3
3       3
4       3

In [15]:
def xavier_init(n_inputs, n_outputs, uniform=True):
    if uniform:
        # 6 was used in the paper.
        init_range = tf.sqrt(6.0 / (n_inputs + n_outputs))
        return tf.random_uniform_initializer(-init_range, init_range)
    else:
        # 3 gives us approximately the same limints as above since this repicks
        # values greater than 2 standard deviations from the mean.
        stddev = tf.sqrt(3.0 / (n_inputs + n_outputs))
        return tf.truncated_normal_initializer(stddev=stddev)

In [18]:
tf.reset_default_graph()

x_data = x_data = df_x1
sess = tf.Session()
y_data = tf.one_hot(df_y, depth = 4).eval(session=sess)
y_data = tf.reshape(y_data, shape=[-1,4]).eval(session=sess)
print(y_data)
tf.set_random_seed(999)  # reproducibility


# parameters
learning_rate = 0.002



X = tf.placeholder(tf.float32, [None, 130])
Y = tf.placeholder(tf.float32, [None, 4])

W1 = tf.get_variable("W1", shape=[130, 64],
                     initializer=xavier_init(130, 64))
b1 = tf.Variable(tf.random_normal([64]))
L1 = tf.nn.relu(tf.matmul(X, W1) + b1)

W2 = tf.get_variable("W2", shape=[64, 64],
                     initializer=xavier_init(64, 64))
b2 = tf.Variable(tf.random_normal([64]))
L2 = tf.nn.relu(tf.matmul(L1, W2) + b2)

W3 = tf.get_variable("W3", shape=[64, 64],
                     initializer=xavier_init(64, 64))
b3 = tf.Variable(tf.random_normal([64]))
L3 = tf.nn.relu(tf.matmul(L2, W3) + b3)

W4 = tf.get_variable("W4", shape=[64, 4],
                     initializer=xavier_init(64, 4))
b4 = tf.Variable(tf.random_normal([4]))
hypothesis = tf.matmul(L3, W4) + b4

# define cost/loss & optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(
    logits=hypothesis, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)
correct_prediction = tf.equal(tf.argmax(hypothesis, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 ...
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]


In [19]:
# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(7001):
    sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
    if step % 1000 == 0 or step < 100:
        loss, acc = sess.run([cost, accuracy], feed_dict={
                             X: x_data, Y: y_data})
        print("Step: {:5}, \t Loss: {:.3f}, \t Acc: {:.2%}".format(
            step, loss, acc))

Step:     0, 	 Loss: 2936.628, 	 Acc: 16.12%
Step:     1, 	 Loss: 1204.348, 	 Acc: 42.32%
Step:     2, 	 Loss: 228.345, 	 Acc: 62.13%
Step:     3, 	 Loss: 440.022, 	 Acc: 62.73%
Step:     4, 	 Loss: 584.241, 	 Acc: 62.74%
Step:     5, 	 Loss: 670.110, 	 Acc: 62.74%
Step:     6, 	 Loss: 712.629, 	 Acc: 62.74%
Step:     7, 	 Loss: 728.866, 	 Acc: 62.55%
Step:     8, 	 Loss: 724.480, 	 Acc: 53.43%
Step:     9, 	 Loss: 711.076, 	 Acc: 29.20%
Step:    10, 	 Loss: 675.386, 	 Acc: 29.07%
Step:    11, 	 Loss: 623.658, 	 Acc: 29.55%
Step:    12, 	 Loss: 561.062, 	 Acc: 42.47%
Step:    13, 	 Loss: 498.524, 	 Acc: 58.85%
Step:    14, 	 Loss: 429.394, 	 Acc: 60.03%
Step:    15, 	 Loss: 354.289, 	 Acc: 55.40%
Step:    16, 	 Loss: 284.788, 	 Acc: 33.45%
Step:    17, 	 Loss: 210.322, 	 Acc: 31.42%
Step:    18, 	 Loss: 487.760, 	 Acc: 15.65%
Step:    19, 	 Loss: 432.360, 	 Acc: 19.08%
Step:    20, 	 Loss: 140.942, 	 Acc: 43.99%
Step:    21, 	 Loss: 180.447, 	 Acc: 63.00%
Step:    22, 	 Loss: 217.688, 

In [20]:
df2_x1 = test.values.tolist()

In [21]:

# Testing & One-hot encoding
test_data = df2_x1


pred_val = sess.run(hypothesis, feed_dict={X: test_data})
pred_idx = sess.run(tf.argmax(pred_val, 1))

# print("predict value : \n {} \n\npredict index : {}".format(pred_val, pred_idx))
print("test data : {} \n\npredict value : \n {} \n\npredict index : {}".format(test_data, pred_val, pred_idx))

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [22]:
pred_idx[:]

array([3, 3, 3, ..., 1, 1, 2], dtype=int64)

In [28]:
submission = pd.DataFrame({'Id' : test_ids, 'Target' : pred_idx+1})
submission.head()

Id  Target
0  ID_2f6873615       4
1  ID_1c78846d2       4
2  ID_e5442cf6a       4
3  ID_a8db26a79       4
4  ID_a62966799       4

In [ ]:
submission.to_csv("submissions.csv", index =False)