## 판다스 형식으로 데이터 불러오기

In [1]:
# 데이터를 판다스를 통해 가공하고자 함
import pandas as pd
df =pd.read_csv('./dataset/train.csv')
len(df)

9557

## 세대주를 선별해 데이터 프레임 만들기 
- "코스타리카 가구 빈곤레벨 측정"이 주제이므로 가구원들은 모두 동일한 빈곤레벨을 지닐것

In [2]:
#가구주인 사람들만 뽑은 데이터 프레임 df_h (parentesco1=1)
df_h = df.loc[df["parentesco1"]==1]
len(df_h)

2973

In [3]:
#결측값은 0으로 제거해주기 
df_h = df_h.fillna(0)

## 결과값 데이터 df_y

In [4]:
# 결과값 데이터에 해당하는 y를 뽑아냄 (타겟)
df_y =pd.DataFrame(df_h["Target"])
df_y.head()

Target
0       4
1       4
2       4
5       4
8       4

## 유의미한 피쳐 데이터 df_x

In [5]:
#결과값 y에 해당하는 값 삭제 
df_x1 = df_h.drop(["Target"],1)
#df_x2 = df_tt.drop(["Target"],1)

#Id 제거
df_x1 = df_x1.drop(["Id"],1)

#집세 제거
df_x1 = df_x1.drop(["v2a1"],1)

#태블릿 유무 제거
df_x1 = df_x1.drop(["v18q"],1)

#가족 구성원 제거
df_x1 = df_x1.drop(["r4h1"],1)
df_x1 = df_x1.drop(["r4h2"],1)
df_x1 = df_x1.drop(["r4h3"],1)
df_x1 = df_x1.drop(["r4m1"],1)
df_x1 = df_x1.drop(["r4m2"],1)
df_x1 = df_x1.drop(["r4m3"],1)

#세대에 함께 사는 사람 수 제거
df_x1 = df_x1.drop(["tamviv"],1)

#학교 늦은 정도 제거
df_x1 = df_x1.drop(["rez_esc"],1)

#세대 수 제거(중복자료)
df_x1 = df_x1.drop(["hhsize"],1)

#지붕 상태 제거(중복자료)
df_x1 = df_x1.drop(["etecho1"],1)
df_x1 = df_x1.drop(["etecho2"],1)
df_x1 = df_x1.drop(["etecho3"],1)


#복도 상태 제거(중복자료)
df_x1 = df_x1.drop(["eviv1"],1)
df_x1 = df_x1.drop(["eviv2"],1)
df_x1 = df_x1.drop(["eviv3"],1)

#성별 제거(중복자료)
df_x1 = df_x1.drop(["female"],1)

#세대주와의 관계열 제거
df_x1 = df_x1.drop(["parentesco1","parentesco2","parentesco3","parentesco4","parentesco5","parentesco6","parentesco7","parentesco8",
                   "parentesco9","parentesco10","parentesco11","parentesco12"],1)

# 세대 식별번호 제거
df_x1 = df_x1.drop(["idhogar"],1)

# 세대 정보 제거
df_x1 = df_x1.drop(["hogar_nin"],1)
df_x1 = df_x1.drop(["hogar_adul"],1)
df_x1 = df_x1.drop(["hogar_mayor"],1)
df_x1 = df_x1.drop(["hogar_total"],1)
df_x1 = df_x1.drop(["dependency"],1)

#세대주성별 교육년수 (논의필요)
df_x1 = df_x1.drop(["edjefe", "edjefa"],1) 

# 지역 정보 (중복)
df_x1 = df_x1.drop(["area2"],1) 

# 나이
df_x1 = df_x1.drop(["age"],1) 

# 제곱 값 제거
df_x1 = df_x1.drop(["SQBescolari", "SQBage", "SQBhogar_total", "SQBedjefe", "SQBhogar_nin",
                    "SQBovercrowding","SQBdependency","SQBmeaned","agesq"],1) 

# 모든 값이 0인 열 제거
df_x1 = df_x1.drop(["elimbasu5", "estadocivil1"],1) 
#여기까지 1000번에 정확도 98프로

# 위까지 90컬럼!



# 상관계수 분석에 따른 열 제거
df_x1 = df_x1.drop(["r4t3","hacapo","tamhog", "pisocemento","overcrowding"],1) 

df_x1.head()

hacdor  rooms  v14a  refrig  v18q1  r4t1  r4t2  escolari  paredblolad  \
0       0      3     1       1    0.0     0     1        10            1   
1       0      4     1       1    1.0     0     1        12            0   
2       0      8     1       1    0.0     0     1        11            0   
5       0      5     1       1    1.0     1     3        11            1   
8       1      2     1       1    0.0     2     2         9            1   

   paredzocalo  ...    television  mobilephone  qmobilephone  lugar1  lugar2  \
0            0  ...             0            1             1       1       0   
1            0  ...             0            1             1       1       0   
2            0  ...             0            0             0       1       0   
5            0  ...             0            1             3       1       0   
8            0  ...             0            1             1       1       0   

   lugar3  lugar4  lugar5  lugar6  area1  
0       0       0       0       0      1  
1       0       0       0       0      1  
2       0       0       0       0      1  
5       0       0       0       0      1  
8       0       0       0       0      1  

[5 rows x 85 columns]

In [6]:
import tensorflow as tf
import numpy as np

C:\Python\Anaconda3-52\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


## xavier와 adam optimizer 활용

In [7]:
def xavier_init(n_inputs, n_outputs, uniform=True):
    if uniform:
        # 6 was used in the paper.
        init_range = tf.sqrt(6.0 / (n_inputs + n_outputs))
        return tf.random_uniform_initializer(-init_range, init_range)
    else:
        # 3 gives us approximately the same limints as above since this repicks
        # values greater than 2 standard deviations from the mean.
        stddev = tf.sqrt(3.0 / (n_inputs + n_outputs))
        return tf.truncated_normal_initializer(stddev=stddev)

## one-hot encoding 위해서 df_y 갯수 -1
- 기존 타겟값 :1,2,3,4
- --> 0,1,2,3 으로 바꿔서 표현해주기 위해

In [8]:
df_y["Target"]=df_y["Target"]-1

In [9]:
# # Review : Learning rate and Evaluation
# import random
# import matplotlib.pyplot as plt

# x_data = df_x1
# sess = tf.Session()
# y_data = tf.one_hot(df_y, depth = 4).eval(session=sess)
# y_data = tf.reshape(y_data, shape=[-1,4]).eval(session=sess)
# print(y_data)
# tf.set_random_seed(999)  # reproducibility


# # parameters
# learning_rate = 0.001



# X = tf.placeholder(tf.float32, [None, 85])
# Y = tf.placeholder(tf.float32, [None, 4])

# W1 = tf.get_variable("W1", shape=[85, 64],
#                      initializer=xavier_init(85, 64))
# b1 = tf.Variable(tf.random_normal([64]))
# L1 = tf.nn.relu(tf.matmul(X, W1) + b1)

# W2 = tf.get_variable("W2", shape=[64, 64],
#                      initializer=xavier_init(64, 64))
# b2 = tf.Variable(tf.random_normal([64]))
# L2 = tf.nn.relu(tf.matmul(L1, W2) + b2)

# W3 = tf.get_variable("W3", shape=[64, 4],
#                      initializer=xavier_init(64, 4))
# b3 = tf.Variable(tf.random_normal([4]))
# hypothesis = tf.matmul(L2, W3) + b3

# # define cost/loss & optimizer
# cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(
#     logits=hypothesis, labels=Y))
# optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)
# correct_prediction = tf.equal(tf.argmax(hypothesis, 1), tf.argmax(Y, 1))
# accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [10]:
# 

# Review : Learning rate and Evaluation
import random
import matplotlib.pyplot as plt

tf.reset_default_graph()

x_data = df_x1
sess = tf.Session()
y_data = tf.one_hot(df_y, depth = 4).eval(session=sess)
y_data = tf.reshape(y_data, shape=[-1,4]).eval(session=sess)
print(y_data)
tf.set_random_seed(999)  # reproducibility



# parameters
learning_rate = 0.001



X = tf.placeholder(tf.float32, [None, 85])
Y = tf.placeholder(tf.float32, [None, 4])
keep_prob = tf.placeholder(tf.float32)


W1 = tf.get_variable("W1", shape=[85, 64], initializer=tf.contrib.layers.xavier_initializer())
b1 = tf.Variable(tf.random_normal([64]))
L1 = tf.nn.relu(tf.matmul(X, W1) + b1)
L1 = tf.nn.dropout(L1, keep_prob=keep_prob)


W2 = tf.get_variable("W2", shape=[64, 64], initializer=tf.contrib.layers.xavier_initializer())
b2 = tf.Variable(tf.random_normal([64]))
L2 = tf.nn.relu(tf.matmul(L1, W2) + b2)
L2 = tf.nn.dropout(L2, keep_prob=keep_prob)

W3 = tf.get_variable("W3", shape=[64, 64], initializer=tf.contrib.layers.xavier_initializer())
b3 = tf.Variable(tf.random_normal([64]))
L3 = tf.nn.relu(tf.matmul(L2, W3) + b3)
L3 = tf.nn.dropout(L3, keep_prob=keep_prob)


W4 = tf.get_variable("W4", shape=[64, 64], initializer=tf.contrib.layers.xavier_initializer())
b4 = tf.Variable(tf.random_normal([64]))
L4 = tf.nn.relu(tf.matmul(L3, W4) + b4)
L4 = tf.nn.dropout(L4, keep_prob=keep_prob)


W5 = tf.get_variable("W5", shape=[64, 4], initializer=tf.contrib.layers.xavier_initializer())
b5 = tf.Variable(tf.random_normal([4]))
L5 = tf.nn.relu(tf.matmul(L4, W5) + b5)

hypothesis = tf.matmul(L4, W5) + b5


# define cost/loss & optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=hypothesis, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)
correct_prediction = tf.equal(tf.argmax(hypothesis, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 ...
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]


In [11]:
# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    sess.run(optimizer, feed_dict={X: x_data, Y: y_data, keep_prob: 0.7})
    if step % 100 == 0 or step < 100:
        loss, acc = sess.run([cost, accuracy], feed_dict={
                             X: x_data, Y: y_data, keep_prob: 0.7})
        print("Step: {:5}, \t Loss: {:.3f}, \t Acc: {:.2%}".format(
            step, loss, acc))

Step:     0, 	 Loss: 2.969, 	 Acc: 17.69%
Step:     1, 	 Loss: 2.569, 	 Acc: 20.59%
Step:     2, 	 Loss: 2.291, 	 Acc: 23.55%
Step:     3, 	 Loss: 2.003, 	 Acc: 28.62%
Step:     4, 	 Loss: 1.771, 	 Acc: 35.89%
Step:     5, 	 Loss: 1.606, 	 Acc: 40.30%
Step:     6, 	 Loss: 1.503, 	 Acc: 47.56%
Step:     7, 	 Loss: 1.505, 	 Acc: 50.79%
Step:     8, 	 Loss: 1.490, 	 Acc: 53.31%
Step:     9, 	 Loss: 1.439, 	 Acc: 56.10%
Step:    10, 	 Loss: 1.439, 	 Acc: 56.04%
Step:    11, 	 Loss: 1.437, 	 Acc: 59.87%
Step:    12, 	 Loss: 1.404, 	 Acc: 60.51%
Step:    13, 	 Loss: 1.412, 	 Acc: 60.95%
Step:    14, 	 Loss: 1.382, 	 Acc: 62.06%
Step:    15, 	 Loss: 1.357, 	 Acc: 61.79%
Step:    16, 	 Loss: 1.370, 	 Acc: 60.68%
Step:    17, 	 Loss: 1.352, 	 Acc: 61.32%
Step:    18, 	 Loss: 1.312, 	 Acc: 61.39%
Step:    19, 	 Loss: 1.281, 	 Acc: 60.24%
Step:    20, 	 Loss: 1.265, 	 Acc: 60.65%
Step:    21, 	 Loss: 1.284, 	 Acc: 60.71%
Step:    22, 	 Loss: 1.242, 	 Acc: 59.70%
Step:    23, 	 Loss: 1.214, 	 Acc:

In [12]:
# df_x1.corr()

In [13]:
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# plt.figure(figsize=(100, 100))

# # Heatmap 설정
# sns.heatmap(df_x1.corr(), linewidths=0.1, vmax=0.5, cmap="coolwarm",
#             linecolor='white', annot=True)

# # 렌더링
# plt.show()

## 변수들간의 correlation 파악 
> - v18q & v18q1 : 0.86 태블릿 유무 겹치는 변수이므로 하나만 사용하기 
> - hhsize & r4h1 :0.45 // hhsize & r4h2 :0.58 // hhsize & r4m1 :0.45 // hhsize & r4m2 :0.64 : 가구원수 타 변수에서 모두 설명하므로 제외하기 
> - 중앙의 상관관계 일정한 형식으로 나온 경우는 벽,지붕,바닥의 좋고나쁨을 표시하는 변수이기에 3개중의 하나만 사용해도 충분 


# train 데이터 중 세대주 아닌 사람들로 정확도 측정해보기

In [48]:
# train 중에서 가구주가 아닌 사람들을 테스트 자료로 활용할 것임.(train-test => tt)
df_tt = df.loc[df["parentesco1"]!=1]
len(df_tt)

6584

In [49]:
df_tt = df_tt.fillna(0)

In [50]:
df_ytt =pd.DataFrame(df_tt["Target"])

In [51]:
#결과값 y에 해당하는 값 삭제 
dtt_x1 = df_tt.drop(["Target"],1)
#dtt_x2 = dtt_tt.drop(["Target"],1)

#Id 제거
dtt_x1 = dtt_x1.drop(["Id"],1)

#집세 제거
dtt_x1 = dtt_x1.drop(["v2a1"],1)

#태블릿 유무 제거
dtt_x1 = dtt_x1.drop(["v18q"],1)

#가족 구성원 제거
dtt_x1 = dtt_x1.drop(["r4h1"],1); dtt_x1 = dtt_x1.drop(["r4h2"],1); dtt_x1 = dtt_x1.drop(["r4h3"],1); dtt_x1 = dtt_x1.drop(["r4m1"],1)
dtt_x1 = dtt_x1.drop(["r4m2"],1); dtt_x1 = dtt_x1.drop(["r4m3"],1)

#세대에 함께 사는 사람 수 제거
dtt_x1 = dtt_x1.drop(["tamviv"],1)

#학교 늦은 정도 제거
dtt_x1 = dtt_x1.drop(["rez_esc"],1)

#세대 수 제거(중복자료)
dtt_x1 = dtt_x1.drop(["hhsize"],1)

#지붕 상태 제거(중복자료)
dtt_x1 = dtt_x1.drop(["etecho1"],1); dtt_x1 = dtt_x1.drop(["etecho2"],1); dtt_x1 = dtt_x1.drop(["etecho3"],1)

#복도 상태 제거(중복자료)
dtt_x1 = dtt_x1.drop(["eviv1"],1); dtt_x1 = dtt_x1.drop(["eviv2"],1); dtt_x1 = dtt_x1.drop(["eviv3"],1)

#성별 제거(중복자료)
dtt_x1 = dtt_x1.drop(["female"],1)

#세대주와의 관계열 제거
dtt_x1 = dtt_x1.drop(["parentesco1","parentesco2","parentesco3","parentesco4","parentesco5","parentesco6","parentesco7","parentesco8",
                   "parentesco9","parentesco10","parentesco11","parentesco12"],1)

# 세대 식별번호 제거
dtt_x1 = dtt_x1.drop(["idhogar"],1)

# 세대 정보 제거
dtt_x1 = dtt_x1.drop(["hogar_nin"],1); dtt_x1 = dtt_x1.drop(["hogar_adul"],1); dtt_x1 = dtt_x1.drop(["hogar_mayor"],1)
dtt_x1 = dtt_x1.drop(["hogar_total"],1); dtt_x1 = dtt_x1.drop(["dependency"],1)

#세대주성별 교육년수 (논의필요)
dtt_x1 = dtt_x1.drop(["edjefe", "edjefa"],1) 

# 지역 정보 (중복)
dtt_x1 = dtt_x1.drop(["area2"],1) 

# 나이
dtt_x1 = dtt_x1.drop(["age"],1) 

# 제곱 값 제거
dtt_x1 = dtt_x1.drop(["SQBescolari", "SQBage", "SQBhogar_total", "SQBedjefe", "SQBhogar_nin",
                    "SQBovercrowding","SQBdependency","SQBmeaned","agesq"],1) 

# 모든 값이 0인 열 제거
dtt_x1 = dtt_x1.drop(["elimbasu5", "estadocivil1"],1) 
#여기까지 1000번에 정확도 98프로

# 위까지 90컬럼!

# 상관계수 분석에 따른 열 제거
dtt_x1 = dtt_x1.drop(["r4t3","hacapo","tamhog", "pisocemento","overcrowding"],1) 

dtt_x1.head()

hacdor  rooms  v14a  refrig  v18q1  r4t1  r4t2  escolari  paredblolad  \
3       0      5     1       1    1.0     1     3         9            1   
4       0      5     1       1    1.0     1     3        11            1   
6       0      5     1       1    1.0     1     3         2            1   
7       1      2     1       1    0.0     2     2         0            1   
9       1      2     1       1    0.0     2     2        11            1   

   paredzocalo  ...    television  mobilephone  qmobilephone  lugar1  lugar2  \
3            0  ...             0            1             3       1       0   
4            0  ...             0            1             3       1       0   
6            0  ...             0            1             3       1       0   
7            0  ...             0            1             1       1       0   
9            0  ...             0            1             1       1       0   

   lugar3  lugar4  lugar5  lugar6  area1  
3       0       0       0       0      1  
4       0       0       0       0      1  
6       0       0       0       0      1  
7       0       0       0       0      1  
9       0       0       0       0      1  

[5 rows x 85 columns]

In [53]:
test_data = dtt_x1
pred_val = sess.run(hypothesis, feed_dict={X: test_data, keep_prob: 1.0})
pred_idx = sess.run(tf.argmax(pred_val, 1))

In [55]:
submission = pd.DataFrame({'Target' : pred_idx + 1})
#submission

In [ ]:
x_data = 
y_data = 

acc = sess.run([cost, accuracy], feed_dict={X: x_data, Y: y_data, keep_prob: 1})
print("Acc: {:.2%}".format(acc))

In [ ]:

comp_pred = tf.equal( tf.arg_max(answer, 1), tf.arg_max(y, 1) )
accuracy = tf.reduce_mean(tf.cast(comp_pred, tf.float32))
acc = sess.run([accuracy], feed_dict = tensor_map)

# test 데이터 가져오기

In [18]:
df_test =pd.read_csv('./dataset/test.csv')
df_test_1 =pd.read_csv('./dataset/test.csv')

In [19]:
df_test.head()

Id      v2a1  hacdor  rooms  hacapo  v14a  refrig  v18q  v18q1  \
0  ID_2f6873615       NaN       0      5       0     1       1     0    NaN   
1  ID_1c78846d2       NaN       0      5       0     1       1     0    NaN   
2  ID_e5442cf6a       NaN       0      5       0     1       1     0    NaN   
3  ID_a8db26a79       NaN       0     14       0     1       1     1    1.0   
4  ID_a62966799  175000.0       0      4       0     1       1     1    1.0   

   r4h1  ...    age  SQBescolari  SQBage  SQBhogar_total  SQBedjefe  \
0     1  ...      4            0      16               9          0   
1     1  ...     41          256    1681               9          0   
2     1  ...     41          289    1681               9          0   
3     0  ...     59          256    3481               1        256   
4     0  ...     18          121     324               1          0   

   SQBhogar_nin  SQBovercrowding  SQBdependency  SQBmeaned  agesq  
0             1             2.25           0.25     272.25     16  
1             1             2.25           0.25     272.25   1681  
2             1             2.25           0.25     272.25   1681  
3             0             1.00           0.00     256.00   3481  
4             1             0.25          64.00        NaN    324  

[5 rows x 142 columns]

In [20]:
# df2_h = df2.loc[df2["parentesco1"]==1]
df_test = df_test.fillna(0)

In [21]:
#Id 제거
df_test = df_test.drop(["Id"],1)

#집세 제거
df_test = df_test.drop(["v2a1"],1)

#태블릿 유무 제거
df_test = df_test.drop(["v18q"],1)

#가족 구성원 제거
df_test = df_test.drop(["r4h1"],1)
df_test = df_test.drop(["r4h2"],1)
df_test = df_test.drop(["r4h3"],1)
df_test = df_test.drop(["r4m1"],1)
df_test = df_test.drop(["r4m2"],1)
df_test = df_test.drop(["r4m3"],1)

#세대에 함께 사는 사람 수 제거
df_test = df_test.drop(["tamviv"],1)

#학교 늦은 정도 제거
df_test = df_test.drop(["rez_esc"],1)

#세대 수 제거(중복자료)
df_test = df_test.drop(["hhsize"],1)

#지붕 상태 제거(중복자료)
df_test = df_test.drop(["etecho1"],1)
df_test = df_test.drop(["etecho2"],1)
df_test = df_test.drop(["etecho3"],1)


#복도 상태 제거(중복자료)
df_test = df_test.drop(["eviv1"],1)
df_test = df_test.drop(["eviv2"],1)
df_test = df_test.drop(["eviv3"],1)

#성별 제거(중복자료)
df_test = df_test.drop(["female"],1)

#세대주와의 관계열 제거
df_test = df_test.drop(["parentesco1","parentesco2","parentesco3","parentesco4","parentesco5","parentesco6","parentesco7","parentesco8",
                   "parentesco9","parentesco10","parentesco11","parentesco12"],1)

# 세대 식별번호 제거
df_test = df_test.drop(["idhogar"],1)

# 세대 정보 제거
df_test = df_test.drop(["hogar_nin"],1)
df_test = df_test.drop(["hogar_adul"],1)
df_test = df_test.drop(["hogar_mayor"],1)
df_test = df_test.drop(["hogar_total"],1)
df_test = df_test.drop(["dependency"],1)

#세대주성별 교육년수 (논의필요)
df_test = df_test.drop(["edjefe", "edjefa"],1) 

# 지역 정보 (중복)
df_test = df_test.drop(["area2"],1) 

# 나이
df_test = df_test.drop(["age"],1) 

# 제곱 값 제거
df_test = df_test.drop(["SQBescolari", "SQBage", "SQBhogar_total", "SQBedjefe", "SQBhogar_nin",
                    "SQBovercrowding","SQBdependency","SQBmeaned","agesq"],1) 

# 모든 값이 0인 열 제거
df_test = df_test.drop(["elimbasu5", "estadocivil1"],1) 
#여기까지 1000번에 정확도 98프로

# 위까지 90컬럼!



# 상관계수 분석에 따른 열 제거
df_test = df_test.drop(["r4t3","hacapo","tamhog", "pisocemento","overcrowding"],1) 

df_test.head()

hacdor  rooms  v14a  refrig  v18q1  r4t1  r4t2  escolari  paredblolad  \
0       0      5     1       1    0.0     1     2         0            1   
1       0      5     1       1    0.0     1     2        16            1   
2       0      5     1       1    0.0     1     2        17            1   
3       0     14     1       1    1.0     0     1        16            1   
4       0      4     1       1    1.0     0     1        11            1   

   paredzocalo  ...    television  mobilephone  qmobilephone  lugar1  lugar2  \
0            0  ...             0            1             2       1       0   
1            0  ...             0            1             2       1       0   
2            0  ...             0            1             2       1       0   
3            0  ...             0            1             2       1       0   
4            0  ...             0            1             1       1       0   

   lugar3  lugar4  lugar5  lugar6  area1  
0       0       0       0       0      1  
1       0       0       0       0      1  
2       0       0       0       0      1  
3       0       0       0       0      1  
4       0       0       0       0      1  

[5 rows x 85 columns]

In [22]:
df_test =  df_test.values.tolist()

In [23]:
# Testing & One-hot encoding
test_data = df_test


pred_val = sess.run(hypothesis, feed_dict={X: test_data, keep_prob: 1.0})
pred_idx = sess.run(tf.argmax(pred_val, 1))

# print("predict value : \n {} \n\npredict index : {}".format(pred_val, pred_idx))
print("test data : {} \n\npredict value : \n {} \n\npredict index : {}".format(test_data, pred_val, pred_idx))

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [24]:
pred_idx[:]

array([3, 3, 3, ..., 3, 3, 3], dtype=int64)

In [25]:
print(pred_idx)

[3 3 3 ... 3 3 3]


In [26]:
len(pred_idx)

23856

In [27]:
len(df_test)

23856

In [28]:
submission = pd.DataFrame({'Id' : df_test_1.Id, 'Target' : pred_idx + 1})
print(submission)

                 Id  Target
0      ID_2f6873615       4
1      ID_1c78846d2       4
2      ID_e5442cf6a       4
3      ID_a8db26a79       4
4      ID_a62966799       4
5      ID_e77d38d45       4
6      ID_3c5f4bd51       4
7      ID_a849c29bd       4
8      ID_472fa82da       4
9      ID_24864adcc       4
10     ID_247909995       4
11     ID_fbe8d0909       4
12     ID_8ed30c46a       4
13     ID_c8809fe15       4
14     ID_b726eb052       4
15     ID_3533dffe1       4
16     ID_67a331b9f       4
17     ID_67c4a6bb6       4
18     ID_8228c6a2e       4
19     ID_d54f1a82e       4
20     ID_a39d40b54       4
21     ID_748724edb       4
22     ID_8be4c9bbf       4
23     ID_7bade887b       4
24     ID_13f752d2b       4
25     ID_a9bff86ae       4
26     ID_04d3ee180       4
27     ID_47e48cb8f       4
28     ID_1615bc9ef       4
29     ID_3bb0b62f1       4
...             ...     ...
23826  ID_2284afed9       4
23827  ID_741c22332       4
23828  ID_34b7a0917       4
23829  ID_bd17c8581 

In [29]:
submission.to_csv("submissions.csv", index =False)