## 판다스 형식으로 데이터 불러오기

In [1]:
# 데이터를 판다스를 통해 가공하고자 함
import pandas as pd
df =pd.read_csv('./dataset/train.csv')

## 세대주를 선별해 데이터 프레임 만들기 
- "코스타리카 가구 빈곤레벨 측정"이 주제이므로 가구원들은 모두 동일한 빈곤레벨을 지닐것

In [2]:
#가구주인 사람들만 뽑은 데이터 프레임 df_h (parentesco1=1)
df_h = df.loc[df["parentesco1"]==1]
df_h.head()

Id      v2a1  hacdor  rooms  hacapo  v14a  refrig  v18q  v18q1  \
0  ID_279628684  190000.0       0      3       0     1       1     0    NaN   
1  ID_f29eb3ddd  135000.0       0      4       0     1       1     1    1.0   
2  ID_68de51c94       NaN       0      8       0     1       1     0    NaN   
5  ID_ec05b1a7b  180000.0       0      5       0     1       1     1    1.0   
8  ID_1284f8aad  130000.0       1      2       0     1       1     0    NaN   

   r4h1   ...    SQBescolari  SQBage  SQBhogar_total  SQBedjefe  SQBhogar_nin  \
0     0   ...            100    1849               1        100             0   
1     0   ...            144    4489               1        144             0   
2     0   ...            121    8464               1          0             0   
5     0   ...            121    1444              16        121             4   
8     0   ...             81     900              16         81             4   

   SQBovercrowding  SQBdependency  SQBmeaned  agesq  Target  
0         1.000000            0.0      100.0   1849       4  
1         1.000000           64.0      144.0   4489       4  
2         0.250000           64.0      121.0   8464       4  
5         1.777778            1.0      121.0   1444       4  
8        16.000000            1.0      100.0    900       4  

[5 rows x 143 columns]

In [3]:
#결측값은 0으로 제거해주기 
df_h = df_h.fillna(0)

## 결과값 데이터 df_y

In [4]:
# 결과값 데이터에 해당하는 y를 뽑아냄 (타겟)
df_y =pd.DataFrame(df_h["Target"])
df_y.head()

Target
0       4
1       4
2       4
5       4
8       4

## 유의미한 피쳐 데이터 df_x

In [5]:
#불필요한 피쳐들 제거해 x1값 만들기 
# age, SQBescolari, SQBage, SQBhogar_total, SQBedjefe, SQBhogar_nin, SQBovercrowding,
# SQBdependency, SQBmeaned, agesq

#결과값 y에 해당하는 값 삭제 
df_x1 = df_h.drop(["Target"],1)
#세대주성별 교육년수 (논의필요)
df_x1 = df_x1.drop(["edjefa", "edjefe"],1) 
#중복정보 제거
df_x1 = df_x1.drop(["dependency","female","area2","hacdor","hacapo","bedrooms","r4h3","r4m3"],1) 
#수학적으로 의미가 없는 값 제거
df_x1 = df_x1.drop(["Id","SQBescolari", "SQBage", "SQBhogar_total", "SQBedjefe", "SQBhogar_nin", "SQBovercrowding","idhogar"],1) 
#세대주와의 관계열 제거
df_x1 = df_x1.drop(["parentesco1","parentesco2","parentesco3","parentesco4","parentesco5","parentesco6","parentesco7","parentesco8",
                   "parentesco9","parentesco10","parentesco11","parentesco12"],1)
#집세 임시제거!!!!!!!!!!!!!!!!!!!!!!!!!!
df_x1 = df_x1.drop(["v2a1"],1)
df_x1.head()

rooms  v14a  refrig  v18q  v18q1  r4h1  r4h2  r4m1  r4m2  r4t1  ...    \
0      3     1       1     0    0.0     0     1     0     0     0  ...     
1      4     1       1     1    1.0     0     1     0     0     0  ...     
2      8     1       1     0    0.0     0     0     0     1     0  ...     
5      5     1       1     1    1.0     0     2     1     1     1  ...     
8      2     1       1     0    0.0     0     1     2     1     2  ...     

   lugar2  lugar3  lugar4  lugar5  lugar6  area1  age  SQBdependency  \
0       0       0       0       0       0      1   43            0.0   
1       0       0       0       0       0      1   67           64.0   
2       0       0       0       0       0      1   92           64.0   
5       0       0       0       0       0      1   38            1.0   
8       0       0       0       0       0      1   30            1.0   

   SQBmeaned  agesq  
0      100.0   1849  
1      144.0   4489  
2      121.0   8464  
5      121.0   1444  
8      100.0    900  

[5 rows x 111 columns]

In [6]:
#새로운열 추가 
# df_x1['rent_to_rooms'] = df_x1['v2a1']/df_x1['rooms']
# df_x1['r4t3_to_rooms'] = df_x1['r4t3']/df_x1['rooms']
# df_x1['rent_to_r4t3'] = df_x1['v2a1']/df_x1['r4t3']
# df_x1['v2a1_to_r4t3'] = df_x1['v2a1']/(df_x1['r4t3'] - df_x1['r4t1'])
df_x1['lent'] = df_x1['tamviv']-df_x1['tamhog']

#열 생성 이후 불필요한 열 제거 
df_x1 = df_x1.drop(["r4t1","r4t2","r4t3","tamhog","tamviv"],1) 
df_x1.head()

rooms  v14a  refrig  v18q  v18q1  r4h1  r4h2  r4m1  r4m2  escolari  ...   \
0      3     1       1     0    0.0     0     1     0     0        10  ...    
1      4     1       1     1    1.0     0     1     0     0        12  ...    
2      8     1       1     0    0.0     0     0     0     1        11  ...    
5      5     1       1     1    1.0     0     2     1     1        11  ...    
8      2     1       1     0    0.0     0     1     2     1         9  ...    

   lugar3  lugar4  lugar5  lugar6  area1  age  SQBdependency  SQBmeaned  \
0       0       0       0       0      1   43            0.0      100.0   
1       0       0       0       0      1   67           64.0      144.0   
2       0       0       0       0      1   92           64.0      121.0   
5       0       0       0       0      1   38            1.0      121.0   
8       0       0       0       0      1   30            1.0      100.0   

   agesq  lent  
0   1849     0  
1   4489     0  
2   8464     0  
5   1444     0  
8    900     0  

[5 rows x 107 columns]

In [7]:
from tqdm import tqdm_notebook
import tensorflow as tf
import numpy as np

C:\Python\Anaconda3-52\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [23]:
# #112개의 피쳐
# tf.set_random_seed(777)  # for reproducibility

# # Predicting animal type based on various features

# x_data = df_x1
# y_data = df_y 

# nb_classes = 4  # 1 ~ 4

# X = tf.placeholder(tf.float32, [None, 107])
# Y = tf.placeholder(tf.int32, [None, 1])  # 1 ~ 4

# Y_one_hot = tf.one_hot(Y, nb_classes)  # one hot
# print("\none_hot", Y_one_hot)

# Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])
# print("\nreshape", Y_one_hot)

# W = tf.Variable(tf.random_normal([107, nb_classes]), name='weight')
# b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# # tf.nn.softmax computes softmax activations
# # softmax = exp(logits) / reduce_sum(exp(logits), dim)
# logits = tf.matmul(X, W) + b
# hypothesis = tf.nn.softmax(logits)

# # Cross entropy cost/loss
# cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits,
#                                                  labels=Y_one_hot)
# cost = tf.reduce_mean(cost_i)
# prediction = tf.argmax(hypothesis, 1)
# correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot, 1))
# accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [9]:
# optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)
# # Launch the graph in a session.
# sess = tf.Session()

# # Initializes global variables in the graph.
# sess.run(tf.global_variables_initializer())

# for step in range(2000):
#     sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
#     if step % 100 == 0:
#         loss, acc = sess.run([cost, accuracy], feed_dict={
#                              X: x_data, Y: y_data})
#         print("Step: {:5}, \t Loss: {:.3f}, \t Acc: {:.2%}".format(
#             step, loss, acc))

## learning rate 조절해서 정확도를 높이고자 함
-> 정확도가 꾸준히 개선되지 않는 모습 보임

In [10]:
# optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001).minimize(cost)

# #이전과 같은 결과 -> 피쳐값들간의 normalized의 필요성 인지 
# # Launch the graph in a session.
# sess = tf.Session()

# # Initializes global variables in the graph.
# sess.run(tf.global_variables_initializer())

# for step in range(2000):
#     sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
#     if step % 100 == 0:
#         loss, acc = sess.run([cost, accuracy], feed_dict={
#                              X: x_data, Y: y_data})
#         print("Step: {:5}, \t Loss: {:.3f}, \t Acc: {:.2%}".format(
#             step, loss, acc))

## xavier와 adam optimizer 활용

In [11]:
def xavier_init(n_inputs, n_outputs, uniform=True):
    if uniform:
        # 6 was used in the paper.
        init_range = tf.sqrt(6.0 / (n_inputs + n_outputs))
        return tf.random_uniform_initializer(-init_range, init_range)
    else:
        # 3 gives us approximately the same limints as above since this repicks
        # values greater than 2 standard deviations from the mean.
        stddev = tf.sqrt(3.0 / (n_inputs + n_outputs))
        return tf.truncated_normal_initializer(stddev=stddev)

# 가중치 그래프 그리기

In [24]:
# Review : Learning rate and Evaluation
import tensorflow as tf
import random
import matplotlib.pyplot as plt

tf.reset_default_graph()

x_data = df_x1
sess = tf.Session()
y_data = tf.one_hot(df_y, depth = 4).eval(session=sess)
y_data = tf.reshape(y_data, shape=[-1,4]).eval(session=sess)
print(y_data)
tf.set_random_seed(999)  # reproducibility


# parameters
learning_rate = 0.001

X = tf.placeholder(tf.float32, [None, 107])
Y = tf.placeholder(tf.float32, [None, 4])

W1 = tf.get_variable("W1", shape=[107, 4],
                     initializer=xavier_init(107, 4))
b1 = tf.Variable(tf.random_normal([4]))

hypothesis = tf.matmul(X, W1) + b1

# define cost/loss & optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(
    logits=hypothesis, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)
correct_prediction = tf.equal(tf.argmax(hypothesis, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 ...
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]


In [25]:
# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(10001):
    sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
    if step % 1000 == 0 or step < 100:
        loss, acc = sess.run([cost, accuracy], feed_dict={
                             X: x_data, Y: y_data})
        print("Step: {:5}, \t Loss: {:.3f}, \t Acc: {:.2%}".format(
            step, loss, acc))

Step:     0, 	 Loss: 295.329, 	 Acc: 12.45%
Step:     1, 	 Loss: 290.016, 	 Acc: 12.58%
Step:     2, 	 Loss: 284.707, 	 Acc: 12.65%
Step:     3, 	 Loss: 279.403, 	 Acc: 12.71%
Step:     4, 	 Loss: 274.102, 	 Acc: 12.95%
Step:     5, 	 Loss: 268.807, 	 Acc: 13.12%
Step:     6, 	 Loss: 263.518, 	 Acc: 13.49%
Step:     7, 	 Loss: 258.239, 	 Acc: 13.79%
Step:     8, 	 Loss: 252.975, 	 Acc: 14.30%
Step:     9, 	 Loss: 247.723, 	 Acc: 14.67%
Step:    10, 	 Loss: 242.485, 	 Acc: 15.04%
Step:    11, 	 Loss: 237.264, 	 Acc: 15.57%
Step:    12, 	 Loss: 232.062, 	 Acc: 16.11%
Step:    13, 	 Loss: 226.884, 	 Acc: 16.89%
Step:    14, 	 Loss: 221.736, 	 Acc: 17.52%
Step:    15, 	 Loss: 216.615, 	 Acc: 18.10%
Step:    16, 	 Loss: 211.533, 	 Acc: 19.11%
Step:    17, 	 Loss: 206.498, 	 Acc: 19.91%
Step:    18, 	 Loss: 201.518, 	 Acc: 20.85%
Step:    19, 	 Loss: 196.604, 	 Acc: 22.27%
Step:    20, 	 Loss: 191.763, 	 Acc: 23.71%
Step:    21, 	 Loss: 187.006, 	 Acc: 25.06%
Step:    22, 	 Loss: 182.352, 	 

In [26]:
len(sess.run(W1))

107

In [27]:
Weight = sess.run(W1)

In [28]:
Weight = pd.DataFrame(Weight)
Weight.head()

0         1         2         3
0  0.071717 -0.097649 -0.050699 -0.002632
1 -0.172668 -0.213885 -0.113227  0.205031
2 -0.569854  0.009763  0.172249 -0.170910
3 -1.214177 -0.452212 -0.013618  0.712276
4  0.594203  0.064720 -0.030350 -0.057481

In [29]:
Weight.columns=[1,2,3,4]

In [32]:
Weight.index= df_x1.columns
Weight.head()

1         2         3         4
rooms   0.071717 -0.097649 -0.050699 -0.002632
v14a   -0.172668 -0.213885 -0.113227  0.205031
refrig -0.569854  0.009763  0.172249 -0.170910
v18q   -1.214177 -0.452212 -0.013618  0.712276
v18q1   0.594203  0.064720 -0.030350 -0.057481

In [56]:
Weight1 = Weight.sort_values([1], ascending=[False])
Weight2 = Weight.sort_values([2], ascending=[False])
Weight3 = Weight.sort_values([3], ascending=[False])
Weight4 = Weight.sort_values([4], ascending=[False])

In [59]:
W_total = pd.DataFrame({"w1" :  Weight1.head(5).index,"w2" :  Weight2.head(5).index,"w3" :  Weight3.head(5).index,"w4" : Weight4.head(5).index})
W_total

w1           w2             w3          w4
0      techocane    pisonatur      elimbasu4   pisoother
1     instlevel6    elimbasu4      techocane   elimbasu6
2    paredfibras      planpri     instlevel6   techootro
3  energcocinar1  paredfibras      tipovivi4  paredother
4     instlevel7   paredother  energcocinar1  sanitario6

In [57]:
Weight_1 = Weight.sort_values([1], ascending=[True])
Weight_2 = Weight.sort_values([2], ascending=[True])
Weight_3 = Weight.sort_values([3], ascending=[True])
Weight_4 = Weight.sort_values([4], ascending=[True])

In [58]:
W_total_ = pd.DataFrame({"w1" :  Weight_1.head(5).index,"w2" :  Weight_2.head(5).index,"w3" :  Weight_3.head(5).index,"w4" : Weight_4.head(5).index})
W_total_

w1          w2           w3             w4
0     planpri   techocane   sanitario6      elimbasu4
1  paredother  instlevel6       noelec      pisonatur
2   elimbasu4   techootro   paredother     instlevel1
3   elimbasu6   pisoother  paredfibras  energcocinar1
4   techootro   elimbasu6      planpri        rez_esc

## one-hot encoding 위해서 df_y 갯수 -1
- 기존 타겟값 :1,2,3,4
- --> 0,1,2,3 으로 바꿔서 표현해주기 위해

In [12]:
df_y["Target"]=df_y["Target"]-1

In [61]:
tf.reset_default_graph()
# Review : Learning rate and Evaluation
import tensorflow as tf
import random
import matplotlib.pyplot as plt

x_data = x_data = df_x1
sess = tf.Session()
y_data = tf.one_hot(df_y, depth = 4).eval(session=sess)
y_data = tf.reshape(y_data, shape=[-1,4]).eval(session=sess)
print(y_data)
tf.set_random_seed(999)  # reproducibility


# parameters
learning_rate = 0.001



X = tf.placeholder(tf.float32, [None, 107])
Y = tf.placeholder(tf.float32, [None, 4])

W1 = tf.get_variable("W1", shape=[107, 64],
                     initializer=xavier_init(107, 64))
b1 = tf.Variable(tf.random_normal([64]))
L1 = tf.nn.relu(tf.matmul(X, W1) + b1)

W2 = tf.get_variable("W2", shape=[64, 64],
                     initializer=xavier_init(64, 64))
b2 = tf.Variable(tf.random_normal([64]))
L2 = tf.nn.relu(tf.matmul(L1, W2) + b2)

W3 = tf.get_variable("W3", shape=[64, 4],
                     initializer=xavier_init(64, 4))
b3 = tf.Variable(tf.random_normal([4]))
#######hypothesis = tf.matmul(L2, W3) + b3


logits = tf.matmul(L2, W3) + b3
hypothesis = tf.nn.softmax(logits)
# define cost/loss & optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(
    logits=logits, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)
correct_prediction = tf.equal(tf.argmax(hypothesis, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 ...
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]


In [ ]:
# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(10001):
    sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
    if step % 1000 == 0 or step < 100:
        loss, acc = sess.run([cost, accuracy], feed_dict={
                             X: x_data, Y: y_data})
        print("Step: {:5}, \t Loss: {:.3f}, \t Acc: {:.2%}".format(
            step, loss, acc))

Step:     0, 	 Loss: 234.272, 	 Acc: 7.53%
Step:     1, 	 Loss: 189.624, 	 Acc: 7.64%
Step:     2, 	 Loss: 146.773, 	 Acc: 8.17%
Step:     3, 	 Loss: 115.814, 	 Acc: 14.67%
Step:     4, 	 Loss: 91.944, 	 Acc: 14.87%
Step:     5, 	 Loss: 63.076, 	 Acc: 14.87%
Step:     6, 	 Loss: 35.093, 	 Acc: 34.24%
Step:     7, 	 Loss: 43.058, 	 Acc: 65.69%
Step:     8, 	 Loss: 50.807, 	 Acc: 65.72%
Step:     9, 	 Loss: 55.585, 	 Acc: 65.72%
Step:    10, 	 Loss: 57.896, 	 Acc: 65.72%
Step:    11, 	 Loss: 58.300, 	 Acc: 65.72%
Step:    12, 	 Loss: 57.167, 	 Acc: 65.72%
Step:    13, 	 Loss: 54.988, 	 Acc: 65.72%
Step:    14, 	 Loss: 51.709, 	 Acc: 65.72%
Step:    15, 	 Loss: 47.438, 	 Acc: 65.72%
Step:    16, 	 Loss: 42.312, 	 Acc: 65.72%
Step:    17, 	 Loss: 36.435, 	 Acc: 65.72%
Step:    18, 	 Loss: 29.888, 	 Acc: 65.72%
Step:    19, 	 Loss: 22.767, 	 Acc: 65.62%
Step:    20, 	 Loss: 15.157, 	 Acc: 65.49%
Step:    21, 	 Loss: 7.500, 	 Acc: 56.27%
Step:    22, 	 Loss: 12.351, 	 Acc: 14.77%
Step:    23

In [62]:
# 행이 107개의 피쳐, 열이 결과값1,2,3,4
#결과값 1에대한 가중치 중 sort를 통해 파악하기 
#그래프로 분석 
W = pd.DataFrame(W)
W.head()

ValueError: DataFrame constructor not properly called!

In [ ]:
W.columns=[1,2,3,4]
W.index= df_x1.columns

In [ ]:
df_x1.corr()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(100, 100))

# Heatmap 설정
sns.heatmap(df_x1.corr(), linewidths=0.1, vmax=0.5, cmap="coolwarm",
            linecolor='white', annot=True)

# 렌더링
plt.show()

## 변수들간의 correlation 파악 
> - v18q & v18q1 : 0.86 태블릿 유무 겹치는 변수이므로 하나만 사용하기 
> - hhsize & r4h1 :0.45 // hhsize & r4h2 :0.58 // hhsize & r4m1 :0.45 // hhsize & r4m2 :0.64 : 가구원수 타 변수에서 모두 설명하므로 제외하기 
> - 중앙의 상관관계 일정한 형식으로 나온 경우는 벽,지붕,바닥의 좋고나쁨을 표시하는 변수이기에 3개중의 하나만 사용해도 충분 


# test 데이터 가져오기

In [ ]:
#df2 =pd.read_csv('./dataset/test.csv')

In [ ]:
#df2.head()

In [ ]:
df2 = df.loc[df["parentesco1"]!=1]
df2_n = df2.fillna(0)

In [ ]:
df3 = df.loc[df["parentesco1"]!=1]

In [ ]:
#결과값 y에 해당하는 값 삭제 
df2_x1 = df2_n
#세대주성별 교육년수 (논의필요)
df2_x1 = df2_x1.drop(["edjefa", "edjefe"],1) 
#중복정보 제거
df2_x1 = df2_x1.drop(["dependency","female","area2","hacdor","hacapo","bedrooms","r4h3","r4m3"],1) 
#수학적으로 의미가 없는 값 제거
df2_x1 = df2_x1.drop(["Id","SQBescolari", "SQBage", "SQBhogar_total", "SQBedjefe", "SQBhogar_nin", "SQBovercrowding","idhogar"],1) 
#세대주와의 관계열 제거
df2_x1 = df2_x1.drop(["parentesco1","parentesco2","parentesco3","parentesco4","parentesco5","parentesco6","parentesco7","parentesco8",
                   "parentesco9","parentesco10","parentesco11","parentesco12"],1)
df2_x1['lent'] = df2_x1['tamviv']-df2_x1['tamhog']
#집세 임시제거!!!!!!!!!!!!!!!!!!!!!!!!!!
df2_x1 = df2_x1.drop(["v2a1"],1)
df2_x1 = df2_x1.drop(["r4t1","r4t2","r4t3","tamhog","tamviv"],1) 
##새로운변수 추가 

In [ ]:
df2_x1 = df2_x1.drop(["Target"],1) 
df2_x1.head()

In [ ]:
df2_x1 =  df2_x1.values.tolist()

In [ ]:
# Testing & One-hot encoding
test_data = df2_x1


pred_val = sess.run(hypothesis, feed_dict={X: test_data})
pred_idx = sess.run(tf.argmax(pred_val, 1))

# print("predict value : \n {} \n\npredict index : {}".format(pred_val, pred_idx))
print("test data : {} \n\npredict value : \n {} \n\npredict index : {}".format(test_data, pred_val, pred_idx))

In [ ]:
pred_idx[:]

In [ ]:
len(pred_idx)

In [ ]:
len(df2_x1)

In [ ]:
submission = pd.DataFrame({'Id' : df2.Id, 'Target' : pred_idx+ 1, "answer":df3["Target"] })
submission.head()

In [ ]:
# submission.to_csv("submissions_testing.csv", index =False)

In [ ]:
submission["true/false"]= submission["answer"]-submission["Target"]

In [ ]:
submission.head()

In [ ]:
test = submission.loc[submission["true/false"]==0, :]
len(test)

In [ ]:
len(test)/len(submission["answer"])